### PR TITLE
[Bug Fix] Added support for compound octet string

### PR DESCRIPTION
**Pull request by nisargap**
Compound octet strings currently are not covered by the PKCS7 parsing function. For cases such as Apple Attest Validation or MS Crypto API this library can't be used until this is fixed.

See the original PR Patch (it was never merged in) : https://github.com/fullsailor/pkcs7/pull/36

### CODE REVIEW

**Comment by nisargap** [comment]
cc for approval @g-k

**Comment by nisargap** [comment]
cc: @g-k can someone with write access merge? i've been maintaining my own fork for several weeks now, thank you!

**Comment by g-k** [comment]
I don't worked at Mozilla anymore, so I can't land any PRs.

Can't promise anything, but maybe @ajvb can take a look.

**Comment by nisargap** [comment]
cc for approval @ajvb

**Pull request closed without merging**
